### ISSUE TITLE
No module named base_loader

### ISSUE THREAD

**Issue by stewilko84** [vinefeeder/VineFeeder#3]
File "C:\Users\****\Desktop\Vine\VineFeeder\services\ALL4\__init__.py", line 2, in <module>
    from base_loader import BaseLoader
ModuleNotFoundError: No module named 'base_loader'

I'm getting this error when trying to download any video. base_loader.py is in the main VineFeeder folder, and I am running as

py vinefeeder.py

any help would be much appreciated

**Comment by stewilko84** [comment]
Marked as complete still getting the same error...

I have everything installed correctly....

**Comment by vinefeeder** [comment]
You error is NOT a  VineFeeder error. Just to double check I re-cloned the repository and have this result right now..

![Screenshot from 2024-12-25 21-13-51](https://github.com/user-attachments/assets/866b5c9d-73a8-4bee-94b7-334aa3f1f62e)

**Comment by stewilko84** [comment]
You said it isn't a Vinefeeder issue, but it is literally erroring on the ALL4 __init__.py service file.

```
[info] Loaded service: ALL4


Searching for white lies
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\****\Desktop\Python\Scripts\devine.exe\__main__.py", line 4, in <module>
    from devine.core.__main__ import main
  File "C:\Users\****\Desktop\Python\Lib\site-packages\devine\core\__main__.py", line 15, in <module>
    from devine.core.commands import Commands
  File "C:\Users\****\Desktop\Python\Lib\site-packages\devine\core\commands.py", line 18, in <module>
    path.stem: getattr(import_module_by_path(path), path.stem)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\****\Desktop\Python\Lib\site-packages\devine\core\utilities.py", line 84, in import_module_by_path
    spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\****\Desktop\Python\Lib\site-packages\devine\commands\dl.py", line 50, in <module>
    from devine.core.services import Services
  File "C:\Users\****\Desktop\Python\Lib\site-packages\devine\core\services.py", line 18, in <module>
    path.parent.stem: getattr(import_module_by_path(path), path.parent.stem)
                              ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\****\Desktop\Python\Lib\site-packages\devine\core\utilities.py", line 84, in import_module_by_path
    spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\****\Desktop\VineFeeder\services\ALL4\__init__.py", line 2, in <module>
    from base_loader import BaseLoader
ModuleNotFoundError: No module named 'base_loader'
```
![image](https://github.com/user-attachments/assets/83b055b2-1c05-4f1a-8203-66386c7020b3)

This is the folder structure for Vinefeeder. As you can see, I've not moved anything.

It is literally looking for base_loader.py, which is in the main folder, but cannot find it and is throwing the error

**Comment by vinefeeder** [comment]
![Screenshot from 2024-12-26 10-48-19](https://github.com/user-attachments/assets/82516497-25fd-4da0-8fcc-32d93206e81f)
You are now getting tedious. I have no idea why your installation fails, nor is it the fault of software. A new install runs perfectly above. 

The fact it won't run for you is down to you to sort out.  I have no control over your machine and operating system.

Be sure you have the latest Python  (3.12) 
Remove the __pycache__ folder;  that will be compiled again on the next run.  Earlier errors tend to persist there.
Do a Google search for 'python import not found'.
Make sure all the files are complete - if you used git clone to install run 'git pull' in the VineFeeder folder to make sure everything is up-to-date.  These are things you SHOULD have done already without needing directing from me.
And as a belt and braces measure, create an empty file called __init__.py  in the VineFeeder folder. 

Finally, I write code for people who know how to install and use it. If you are not in that group, it is not in my remit to help you. Sort it out yourself and respect my privacy.
